### ISSUE TITLE
Why webscalesql other than google spanner?

### ISSUE THREAD

**Issue by leafonsword** [facebookarchive/webscalesql-5.6#8] opened 2014-04-13 08:39 UTC
I know this place is for issue not for question,but I couldn't found a email or other contact methods~Forgive me^-^
It seems google has F1、spanner such "newsql" products,having very good scalibility,so why do you create webscalesql?

**Comment by byte** [comment] 2014-04-13 14:27
@leafonsword because its clear that mysql is being run at scale at all these companies and its not going anywhere. While Google has written a research paper on spanner, they're not exactly making it opensource. Google has also written research papers on mapreduce and bigtable, and it was up to third party companies to create equivalents.

(this is definitely not a bug, might have been better on the webscalesql@googlegroups.com mailing list - https://groups.google.com/forum/#!forum/webscalesql - I'd close it but I don't have the privileges)

**Comment by steaphangreene** [comment] 2014-04-13 16:57
WebScaleSQL is not a new creation, it is a branch of MySQL specifically designed for the needs we all tend to have when using MySQL at scale.

At scale, we tend to use several different data storage technologies, each for whatever we have found it is most suited for.  MySQL is better for certain use-cases than anything else we each have, and so we expect to continue to use it for those things.

**Closed as completed by steaphangreene** 2014-04-13 16:57 UTC
